[workspace]
members = [
    ".",
    "bindings/python"
]

[package]
name = "visualife"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]
path = "src/lib.rs"

[dependencies]
rand = { version = "0.9.0", features = [] }
rand_distr = "0.5"
clap = { version = "4", features = ["derive"] }
thiserror = "1.0"
anyhow = "1"    # to erase the type of an error returned
indexmap = "2"  # to draw nodes of a mindmap in the same order as they were added / grown
# displaydoc = "0.2"
data-matrix = "0.2.0"
base64 = "0.22.1" # to load data from CSV / column files
